apiVersion: v1
description: Bookinfo Details Service Helm Chart
name: bookinfo-details
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo.dev.opsta.net/student106/details
maintainers:
  - name: student106
    email: devop106@mail.kmutt.ac.th
sources:
  - https://github.com/artidsun/bookinfo-details